// <auto-generated />
namespace DTT.LRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditBookReaderUsingEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditBookReaderUsingEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202107040630105_Edit-BookReaderUsingEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
